---
- include_vars:         '../roles/mail-server/vars/dkim_public_key.yml'
- include_tasks:        '../tasks/system_groups.yml'
- include_tasks:        '../tasks/system_users.yml'
- include_tasks:        '../tasks/authorized_keys.yml'
- include_tasks:        '../tasks/allow_users.yml'
- include_tasks:        '../tasks/install_packages.yml'
# https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=860064
- include_tasks:        '../tasks/install_files.yml'
- include_tasks:        '../tasks/template_files.yml'
- include_tasks:        '../tasks/create_files.yml'
- include_tasks:        '../tasks/enable_services.yml'
- include_tasks:        '../tasks/start_services.yml'
- include_tasks:        '../tasks/restart_services.yml'
  when:                 install_files_result.changed
                        or template_files_result.changed
#- include_tasks:        '../tasks/commands.yml'
#  changed_when:         false
