---
- include:              '../tasks/system_groups.yml'
- include:              '../tasks/system_users.yml'
- include:              '../tasks/authorized_keys.yml'
- include:              '../tasks/allow_users.yml'
- include:              '../tasks/install_packages.yml'
- include:              '../tasks/remove_packages.yml'
- include:              '../tasks/install_files.yml'
- include:              '../tasks/enable_services.yml'
- include:              '../tasks/start_services.yml'
- include:              '../tasks/restart_services.yml'
  when:                 install_files_result.changed
